module.exports = {
    tracker_title: "Kotya Calendar",
    history_title: "Kotya History",
    tasks_title: "Kotya Tasks",

    id: "ID",
    id_dt: "ID:",
    external_id: "#",

    duplicate_external_id: "number already exists",
    fill_the_fields: "fill the fields",
    are_you_sure: "are you sure?",
    updated_status: "updated status",

    week: "week",
    new: "new",
    add: "add",
    search: "search",
    delete: "delete",
    total: "total",
    total_dt: "total:",

    monday: "monday",
    tuesday: "tuesday",
    wednesday: "wednesday",
    thursday: "thursday",
    friday: "friday",
    saturday: "saturday",
    sunday: "sunday",
    create: "create",
    created: "created",
    created_dt: "created:",
    updated: "updated",
    updated_dt: "updated:",

    time: "time",
    task: "task",
    tasks: "tasks",

    page_first: "First",
    page_prev: "Previous",
    page_next: "Next",
    page_last: "Last",
    page_total: "Total:",
    page_current: "Current:",
    page: "page",

    history: "history",
    tracker: "calendar",
    track_created: "Track created",
    track_updated: "Track updated",
    track_deleted: "Track deleted",

    name: "name",
    name_dt: "name:",
    status: "status",
    status_dt: "status:",
    begin: "Start",
    started: "started",
    end: "finish",
    ended: "finished",
    deleted: "deleted",
    force_end: "auto finished",

    pause: "pause",
    inpause: "on pause",
    inwork: "in work",
    complete: "done",

    wasted: "spent",
    wasted_dt: "spent:",
    wasted_per_start_dt: ":",
    wasted_per_task_dt: "spent for task:",
    wasted_per_day_dt: "spent for day:",
};
