module.exports = {
    tracker_title: "Kotya Календарь",
    history_title: "Kotya История",
    tasks_title: "Kotya Таски",

    id: "ID",
    id_dt: "ID:",
    external_id: "#",

    duplicate_external_id: "номер уже существует",
    fill_the_fields: "заполните поля",
    are_you_sure: "вы уверены?",
    updated_status: "обновлён статус",

    week: "неделя",
    new: "новый",
    add: "добавить",
    search: "поиск",
    delete: "удалить",
    total: "всего",
    total_dt: "всего:",

    monday: "понедельник",
    tuesday: "вторник",
    wednesday: "среда",
    thursday: "четверг",
    friday: "пятница",
    saturday: "суббота",
    sunday: "воскресенье",
    create: "создать",
    created: "создан",
    created_dt: "создан:",
    updated: "обновлён",
    updated_dt: "обновлён:",

    time: "время",
    task: "таск",
    tasks: "таски",

    page_first: "первая",
    page_prev: "предыдущая",
    page_next: "следующая",
    page_last: "последняя",
    page_total: "всего:",
    page_current: "текущая:",
    page: "страница",

    history: "история",
    tracker: "календарь",
    track_created: "Трэк создан",
    track_updated: "Трэк обновлён",
    track_deleted: "Трэк удалён",

    name: "имя",
    name_dt: "имя:",
    status: "статус",
    status_dt: "статус:",
    begin: "начать",
    started: 'начат',
    end: "закончить",
    ended: "закончен",
    deleted: "удалён",
    force_end: "закончен автоматически",

    pause: "пауза",
    inpause: "в паузе",
    inwork: "в работе",
    complete: "выполнено",

    wasted: "затрачено",
    wasted_dt: "затрачено:",
    wasted_per_start_dt: ":",
    wasted_per_task_dt: "затрачено за таск:",
    wasted_per_day_dt: "затрачено за день:",
};
